require_relative 'spec_helper'

describe Converter do

  describe ".stringify" do

    it "converts numbers up to 63" do
      expect(Converter.stringify(0)).to eq("0")
      expect(Converter.stringify(1)).to eq("1")
      expect(Converter.stringify(2)).to eq("2")
      expect(Converter.stringify(3)).to eq("3")
      expect(Converter.stringify(4)).to eq("4")
      expect(Converter.stringify(5)).to eq("5")
      expect(Converter.stringify(6)).to eq("6")
      expect(Converter.stringify(7)).to eq("7")
      expect(Converter.stringify(8)).to eq("8")
      expect(Converter.stringify(9)).to eq("9")
      expect(Converter.stringify(10)).to eq("a")
      expect(Converter.stringify(11)).to eq("b")
      expect(Converter.stringify(12)).to eq("c")
      expect(Converter.stringify(13)).to eq("d")
      expect(Converter.stringify(14)).to eq("e")
      expect(Converter.stringify(15)).to eq("f")
      expect(Converter.stringify(16)).to eq("g")
      expect(Converter.stringify(17)).to eq("h")
      expect(Converter.stringify(18)).to eq("i")
      expect(Converter.stringify(19)).to eq("j")
      expect(Converter.stringify(20)).to eq("k")
      expect(Converter.stringify(21)).to eq("l")
      expect(Converter.stringify(22)).to eq("m")
      expect(Converter.stringify(23)).to eq("n")
      expect(Converter.stringify(24)).to eq("o")
      expect(Converter.stringify(25)).to eq("p")
      expect(Converter.stringify(26)).to eq("q")
      expect(Converter.stringify(27)).to eq("r")
      expect(Converter.stringify(28)).to eq("s")
      expect(Converter.stringify(29)).to eq("t")
      expect(Converter.stringify(30)).to eq("u")
      expect(Converter.stringify(31)).to eq("v")
      expect(Converter.stringify(32)).to eq("w")
      expect(Converter.stringify(33)).to eq("x")
      expect(Converter.stringify(34)).to eq("y")
      expect(Converter.stringify(35)).to eq("z")
      expect(Converter.stringify(36)).to eq("A")
      expect(Converter.stringify(37)).to eq("B")
      expect(Converter.stringify(38)).to eq("C")
      expect(Converter.stringify(39)).to eq("D")
      expect(Converter.stringify(40)).to eq("E")
      expect(Converter.stringify(41)).to eq("F")
      expect(Converter.stringify(42)).to eq("G")
      expect(Converter.stringify(43)).to eq("H")
      expect(Converter.stringify(44)).to eq("I")
      expect(Converter.stringify(45)).to eq("J")
      expect(Converter.stringify(46)).to eq("K")
      expect(Converter.stringify(47)).to eq("L")
      expect(Converter.stringify(48)).to eq("M")
      expect(Converter.stringify(49)).to eq("N")
      expect(Converter.stringify(50)).to eq("O")
      expect(Converter.stringify(51)).to eq("P")
      expect(Converter.stringify(52)).to eq("Q")
      expect(Converter.stringify(53)).to eq("R")
      expect(Converter.stringify(54)).to eq("S")
      expect(Converter.stringify(55)).to eq("T")
      expect(Converter.stringify(56)).to eq("U")
      expect(Converter.stringify(57)).to eq("V")
      expect(Converter.stringify(58)).to eq("W")
      expect(Converter.stringify(59)).to eq("X")
      expect(Converter.stringify(60)).to eq("Y")
      expect(Converter.stringify(61)).to eq("Z")
      expect(Converter.stringify(62)).to eq("-")
      expect(Converter.stringify(63)).to eq("_")
    end

    it "converts numbers 64-127" do
      expect(Converter.stringify(64)).to eq("10")
      expect(Converter.stringify(65)).to eq("11")
      expect(Converter.stringify(66)).to eq("12")
      expect(Converter.stringify(67)).to eq("13")
      expect(Converter.stringify(68)).to eq("14")
      expect(Converter.stringify(69)).to eq("15")
      expect(Converter.stringify(70)).to eq("16")
      expect(Converter.stringify(71)).to eq("17")
      expect(Converter.stringify(72)).to eq("18")
      expect(Converter.stringify(73)).to eq("19")
      expect(Converter.stringify(74)).to eq("1a")
      expect(Converter.stringify(75)).to eq("1b")
      expect(Converter.stringify(76)).to eq("1c")
      expect(Converter.stringify(77)).to eq("1d")
      expect(Converter.stringify(78)).to eq("1e")
      expect(Converter.stringify(79)).to eq("1f")
      expect(Converter.stringify(80)).to eq("1g")
      expect(Converter.stringify(81)).to eq("1h")
      expect(Converter.stringify(82)).to eq("1i")
      expect(Converter.stringify(83)).to eq("1j")
      expect(Converter.stringify(84)).to eq("1k")
      expect(Converter.stringify(85)).to eq("1l")
      expect(Converter.stringify(86)).to eq("1m")
      expect(Converter.stringify(87)).to eq("1n")
      expect(Converter.stringify(88)).to eq("1o")
      expect(Converter.stringify(89)).to eq("1p")
      expect(Converter.stringify(90)).to eq("1q")
      expect(Converter.stringify(91)).to eq("1r")
      expect(Converter.stringify(92)).to eq("1s")
      expect(Converter.stringify(93)).to eq("1t")
      expect(Converter.stringify(94)).to eq("1u")
      expect(Converter.stringify(95)).to eq("1v")
      expect(Converter.stringify(96)).to eq("1w")
      expect(Converter.stringify(97)).to eq("1x")
      expect(Converter.stringify(98)).to eq("1y")
      expect(Converter.stringify(99)).to eq("1z")
      expect(Converter.stringify(100)).to eq("1A")
      expect(Converter.stringify(101)).to eq("1B")
      expect(Converter.stringify(102)).to eq("1C")
      expect(Converter.stringify(103)).to eq("1D")
      expect(Converter.stringify(104)).to eq("1E")
      expect(Converter.stringify(105)).to eq("1F")
      expect(Converter.stringify(106)).to eq("1G")
      expect(Converter.stringify(107)).to eq("1H")
      expect(Converter.stringify(108)).to eq("1I")
      expect(Converter.stringify(109)).to eq("1J")
      expect(Converter.stringify(110)).to eq("1K")
      expect(Converter.stringify(111)).to eq("1L")
      expect(Converter.stringify(112)).to eq("1M")
      expect(Converter.stringify(113)).to eq("1N")
      expect(Converter.stringify(114)).to eq("1O")
      expect(Converter.stringify(115)).to eq("1P")
      expect(Converter.stringify(116)).to eq("1Q")
      expect(Converter.stringify(117)).to eq("1R")
      expect(Converter.stringify(118)).to eq("1S")
      expect(Converter.stringify(119)).to eq("1T")
      expect(Converter.stringify(120)).to eq("1U")
      expect(Converter.stringify(121)).to eq("1V")
      expect(Converter.stringify(122)).to eq("1W")
      expect(Converter.stringify(123)).to eq("1X")
      expect(Converter.stringify(124)).to eq("1Y")
      expect(Converter.stringify(125)).to eq("1Z")
      expect(Converter.stringify(126)).to eq("1-")
      expect(Converter.stringify(127)).to eq("1_")
    end

    it "converts 128" do
      expect(Converter.stringify(128)).to eq("20")
    end

    it "converts 281,474,976,710,656" do
      expect(Converter.stringify(281_474_976_710_656)).to eq("100000000")
    end

  end

  describe ".integerize" do
    it "converts numbers up to 63" do
      expect(Converter.integerize("0")).to eq(0)
      expect(Converter.integerize("1")).to eq(1)
      expect(Converter.integerize("2")).to eq(2)
      expect(Converter.integerize("3")).to eq(3)
      expect(Converter.integerize("4")).to eq(4)
      expect(Converter.integerize("5")).to eq(5)
      expect(Converter.integerize("6")).to eq(6)
      expect(Converter.integerize("7")).to eq(7)
      expect(Converter.integerize("8")).to eq(8)
      expect(Converter.integerize("9")).to eq(9)
      expect(Converter.integerize("a")).to eq(10)
      expect(Converter.integerize("b")).to eq(11)
      expect(Converter.integerize("c")).to eq(12)
      expect(Converter.integerize("d")).to eq(13)
      expect(Converter.integerize("e")).to eq(14)
      expect(Converter.integerize("f")).to eq(15)
      expect(Converter.integerize("g")).to eq(16)
      expect(Converter.integerize("h")).to eq(17)
      expect(Converter.integerize("i")).to eq(18)
      expect(Converter.integerize("j")).to eq(19)
      expect(Converter.integerize("k")).to eq(20)
      expect(Converter.integerize("l")).to eq(21)
      expect(Converter.integerize("m")).to eq(22)
      expect(Converter.integerize("n")).to eq(23)
      expect(Converter.integerize("o")).to eq(24)
      expect(Converter.integerize("p")).to eq(25)
      expect(Converter.integerize("q")).to eq(26)
      expect(Converter.integerize("r")).to eq(27)
      expect(Converter.integerize("s")).to eq(28)
      expect(Converter.integerize("t")).to eq(29)
      expect(Converter.integerize("u")).to eq(30)
      expect(Converter.integerize("v")).to eq(31)
      expect(Converter.integerize("w")).to eq(32)
      expect(Converter.integerize("x")).to eq(33)
      expect(Converter.integerize("y")).to eq(34)
      expect(Converter.integerize("z")).to eq(35)
      expect(Converter.integerize("A")).to eq(36)
      expect(Converter.integerize("B")).to eq(37)
      expect(Converter.integerize("C")).to eq(38)
      expect(Converter.integerize("D")).to eq(39)
      expect(Converter.integerize("E")).to eq(40)
      expect(Converter.integerize("F")).to eq(41)
      expect(Converter.integerize("G")).to eq(42)
      expect(Converter.integerize("H")).to eq(43)
      expect(Converter.integerize("I")).to eq(44)
      expect(Converter.integerize("J")).to eq(45)
      expect(Converter.integerize("K")).to eq(46)
      expect(Converter.integerize("L")).to eq(47)
      expect(Converter.integerize("M")).to eq(48)
      expect(Converter.integerize("N")).to eq(49)
      expect(Converter.integerize("O")).to eq(50)
      expect(Converter.integerize("P")).to eq(51)
      expect(Converter.integerize("Q")).to eq(52)
      expect(Converter.integerize("R")).to eq(53)
      expect(Converter.integerize("S")).to eq(54)
      expect(Converter.integerize("T")).to eq(55)
      expect(Converter.integerize("U")).to eq(56)
      expect(Converter.integerize("V")).to eq(57)
      expect(Converter.integerize("W")).to eq(58)
      expect(Converter.integerize("X")).to eq(59)
      expect(Converter.integerize("Y")).to eq(60)
      expect(Converter.integerize("Z")).to eq(61)
      expect(Converter.integerize("-")).to eq(62)
      expect(Converter.integerize("_")).to eq(63)
      
    end

    it "converts numbers 64-127" do
      expect(Converter.integerize("10")).to eq(64)
      expect(Converter.integerize("11")).to eq(65)
      expect(Converter.integerize("12")).to eq(66)
      expect(Converter.integerize("13")).to eq(67)
      expect(Converter.integerize("14")).to eq(68)
      expect(Converter.integerize("15")).to eq(69)
      expect(Converter.integerize("16")).to eq(70)
      expect(Converter.integerize("17")).to eq(71)
      expect(Converter.integerize("18")).to eq(72)
      expect(Converter.integerize("19")).to eq(73)
      expect(Converter.integerize("1a")).to eq(74)
      expect(Converter.integerize("1b")).to eq(75)
      expect(Converter.integerize("1c")).to eq(76)
      expect(Converter.integerize("1d")).to eq(77)
      expect(Converter.integerize("1e")).to eq(78)
      expect(Converter.integerize("1f")).to eq(79)
      expect(Converter.integerize("1g")).to eq(80)
      expect(Converter.integerize("1h")).to eq(81)
      expect(Converter.integerize("1i")).to eq(82)
      expect(Converter.integerize("1j")).to eq(83)
      expect(Converter.integerize("1k")).to eq(84)
      expect(Converter.integerize("1l")).to eq(85)
      expect(Converter.integerize("1m")).to eq(86)
      expect(Converter.integerize("1n")).to eq(87)
      expect(Converter.integerize("1o")).to eq(88)
      expect(Converter.integerize("1p")).to eq(89)
      expect(Converter.integerize("1q")).to eq(90)
      expect(Converter.integerize("1r")).to eq(91)
      expect(Converter.integerize("1s")).to eq(92)
      expect(Converter.integerize("1t")).to eq(93)
      expect(Converter.integerize("1u")).to eq(94)
      expect(Converter.integerize("1v")).to eq(95)
      expect(Converter.integerize("1w")).to eq(96)
      expect(Converter.integerize("1x")).to eq(97)
      expect(Converter.integerize("1y")).to eq(98)
      expect(Converter.integerize("1z")).to eq(99)
      expect(Converter.integerize("1A")).to eq(100)
      expect(Converter.integerize("1B")).to eq(101)
      expect(Converter.integerize("1C")).to eq(102)
      expect(Converter.integerize("1D")).to eq(103)
      expect(Converter.integerize("1E")).to eq(104)
      expect(Converter.integerize("1F")).to eq(105)
      expect(Converter.integerize("1G")).to eq(106)
      expect(Converter.integerize("1H")).to eq(107)
      expect(Converter.integerize("1I")).to eq(108)
      expect(Converter.integerize("1J")).to eq(109)
      expect(Converter.integerize("1K")).to eq(110)
      expect(Converter.integerize("1L")).to eq(111)
      expect(Converter.integerize("1M")).to eq(112)
      expect(Converter.integerize("1N")).to eq(113)
      expect(Converter.integerize("1O")).to eq(114)
      expect(Converter.integerize("1P")).to eq(115)
      expect(Converter.integerize("1Q")).to eq(116)
      expect(Converter.integerize("1R")).to eq(117)
      expect(Converter.integerize("1S")).to eq(118)
      expect(Converter.integerize("1T")).to eq(119)
      expect(Converter.integerize("1U")).to eq(120)
      expect(Converter.integerize("1V")).to eq(121)
      expect(Converter.integerize("1W")).to eq(122)
      expect(Converter.integerize("1X")).to eq(123)
      expect(Converter.integerize("1Y")).to eq(124)
      expect(Converter.integerize("1Z")).to eq(125)
      expect(Converter.integerize("1-")).to eq(126)
      expect(Converter.integerize("1_")).to eq(127)
    end

    it "converts 128" do
      expect(Converter.integerize("20")).to eq(128)
    end

    it "converts 281,474,976,710,656" do
      expect(Converter.integerize("100000000")).to eq(281_474_976_710_656)
    end
  end

  it "can convert back and forth up to 1mm" do
    1_000_000.times do |i|
      expect(Converter.integerize(Converter.stringify(i))).to eq(i)
    end
  end

end